name: practice
networks:
  practice_network:
    driver: bridge
services:
  postgres:
    image: postgres
    container_name: '${PG_CONTAINER_NAME}'
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '${POSTGRES_PORT}'
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - practice_network
  pgadmin-ui:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '8090:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
    networks:
      - practice_network  

volumes:
  pgdata:
